parameters:
    url_shortener.domain: '%env(URL_SHORTENER_DOMAIN)%'
    url_shortener.min_length: '%env(int:URL_SHORTENER_MIN_LENGTH)%'
    url_shortener.max_age: '%env(int:URL_SHORTENER_MAX_AGE)%'

services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\UrlEncoder:
        arguments:
            $minLength: '%url_shortener.min_length%'
            
    App\Service\UrlService:
        arguments:
            $urlRepository: '@App\Repository\UrlRepository'
            $urlEncoder: '@App\Service\UrlEncoder'
            $params: '@parameter_bag'
