version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: url-shortener-backend
    volumes:
      - ./backend:/var/www/html
      - ./backend/var:/var/www/html/var
    environment:
      - APP_ENV=dev
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
      - URL_SHORTENER_DOMAIN=localhost:8000
    ports:
      - "8000:80"
    networks:
      - url-shortener-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: url-shortener-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - url-shortener-network
    command: npm run dev -- --host 0.0.0.0

networks:
  url-shortener-network:
    driver: bridge