version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: url-shortener-backend
    volumes:
      - ./backend:/var/www/html
      - ./backend/var:/var/www/html/var
    environment:
      - APP_ENV=dev
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
      - URL_SHORTENER_DOMAIN=localhost:8000
    ports:
      - "8000:80"
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge